mode = "dark"

accent = "#33b1ff"
hyprland_active_border = "#9a7082"
selection = "#41414d"
muted = "#525252"

background = "#161616"
dark_background = "#101010"
darker_background = "#0c0c0c"
lighter_background = "#262626"

foreground = "#f2f4f8"
dark_foreground = "#525252"
light_foreground = "#dde1e6"
bright_foreground = "#f2f4f8"

red = "#3ddbd9"
yellow = "#ee5396"
orange = "#9597b7"
green = "#33b1ff"
cyan = "#ff7eb6"
blue = "#42be65"
magenta = "#be95ff"
brown = "#4a4b5b"

bright_red = "#78a9ff"
bright_yellow = "#be95ff"
bright_green = "#ff7eb6"
bright_cyan = "#82cfff"
bright_blue = "#dde1e6"
bright_magenta = "#ffffff"
